---
title: "Data Preprocessing"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

## Get Followers From Twitter
Iteratively retrieve follower lists of the 36 newspaper accounts.
```{r message=FALSE, warning=FALSE}
library(rtweet)

twitterIDs <- c("FinancialTimes", "FT", "guardiannews", "guardian", "MailOnline", "DailyMailUK ", "Telegraph", "Fabulousmag", "TheSun", "thetimes", "DailyMirror", "Daily_Express", "EveningStandard", "standardnews", "standardsport", "standardcity", "MENnewsdesk", "LivEchonews", "TheArtNewspaper", "MetroUK", "MetroScotland", "timeshighered", "birmingham_live", "WalesOnline", "RacingPost", "LeedsNews", "dailystar", "DStarPics", "ChronicleLive", "BelTel", "TheStage", "TheScotsman", "SheffieldStar", "edinburghpaper", "surreylive", "ExpressandStar")
dir.create("Follower lists", showWarnings = F)

for (name in twitterIDs){
  print(name)
  
  id <- lookup_users(name)$user_id
  followers <- get_followers(user = id, n = Inf, retryonratelimit = T)
  save(followers, file = paste0("Follower lists/", name, ".RData"))
}

```